apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-kubernetes
  labels:
    name:  hello-kubernetes
spec:
  revisionHistoryLimit: 3
  minReadySeconds: 10
  progressDeadlineSeconds: 30
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: hello-kubernetes
  template:
    metadata:
      labels:
        name:  hello-kubernetes
    spec:
      containers:
      - image:  paulbower/hello-kubernetes:1.18
        name:  hello-kubernetes
        ports:
        - containerPort:  80
          name:  http
      restartPolicy: Always
