apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  selector:
    name: hello-kubernetes
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
