apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: sleep-world
        image: busybox
        args: ["20"]
        command: ["sleep"]
      restartPolicy: Never
  completions: 10
  backoffLimit: 3
  parallelism: 5
