apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: sleep-world
        image: busybox
        command: ["sleep", "20"]
      restartPolicy: Never
  completions: 20
  backoffLimit: 3
  parallelism: 5
