apiVersion: v1
kind: Pod
metadata:
  name: web-1
  labels:
    app: web-1
spec:
  containers:
    - name: web-first
      image: nginx:1.19.1
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
